# Generated by Django 5.0.6 on 2024-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestra', '0003_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
