# Generated by Django 5.0.6 on 2024-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestra', '0005_alter_personaltraining_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptrainingreview',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='grouptrainingreview',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaltrainingreview',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='personaltrainingreview',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
