# Generated by Django 5.0.6 on 2024-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_grouptraining_title'),
        ('palestra', '0007_completedgrouptrainingreservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='fitness_goals',
            field=models.ManyToManyField(to='management.fitnessgoal'),
        ),
    ]
